Changed link in RPM generation and new init.d script

diff --git a/flume/neore/rpm/SOURCES/init.d/cygnus b/flume/neore/rpm/SOURCES/init.d/cygnus
--- a/flume/neore/rpm/SOURCES/init.d/cygnus
+++ b/flume/neore/rpm/SOURCES/init.d/cygnus
@@ -29,66 +29,118 @@ COMPONENT_NAME=cygnus
 PREFIX=/usr
 CYGNUS_DIR=${PREFIX}/cygnus
 FLUME_EXECUTABLE=${CYGNUS_DIR}/bin/cygnus-flume-ng
-CYGNUS_PID_FILE=/var/run/cygnus/cygnus.pid
 CYGNUS_USER=cygnus
-CYGNUS_PROCESS=java
-
-# Load the environment
- if [[ -f ${CYGNUS_DIR}/conf/flume.conf ]]; then
-    . ${CYGNUS_DIR}/conf/flume.conf
-else
-   echo "Configuration file ${CYGNUS_DIR}/conf/flume.conf not found"
-   exit 1
-fi
 
 cygnus_start()
 {
-    printf "%-50s" "Starting ${NAME}..."
-    if [[ -x ${FLUME_EXECUTABLE} ]]; then
-        CYGNUS_COMMAND="${FLUME_EXECUTABLE} agent --conf ${CONFIG_FOLDER} -f ${CONFIG_FILE} -n ${AGENT_NAME} &> /dev/null & echo \$! > $CYGNUS_PID_FILE"
+    local result=0
+
+    if [[ ! -x ${FLUME_EXECUTABLE} ]]; then
+        printf "%s\n" "Fail - ${FLUME_EXECUTABLE} not exists or is not executable."
+        exit 1
+    fi
+
+    for instance in $(ls ${CYGNUS_DIR}/conf/cygnus_instance_*.conf)
+    do
+        local NAME
+        NAME=${instance%.conf}
+        NAME=${NAME#*cygnus_instance_}
+
+        . ${instance}
+        
+        CYGNUS_PID_FILE="/var/run/cygnus/cygnus_${NAME}.pid"
+        
+        printf "%s" "Starting Cygnus ${NAME}...  "
+
+        status -p ${CYGNUS_PID_FILE} ${FLUME_EXECUTABLE} &> /dev/null 
+
+        if [[ ${?} -eq 0 ]]; then
+            printf "%s\n" " Already running, skipping $(success)"
+            continue
+        fi
+
+        CYGNUS_COMMAND="${FLUME_EXECUTABLE} agent -p ${ADMIN_PORT} --conf ${CONFIG_FOLDER} -f ${CONFIG_FILE} -n ${AGENT_NAME}  -Dflume.log.file=${LOGFILE_NAME} &>> /var/log/cygnus/${LOGFILE_NAME} & echo \$! > ${CYGNUS_PID_FILE}"
         su ${CYGNUS_USER} -c "${CYGNUS_COMMAND}"
         sleep 2 # wait some time to know if flume is still alive
-        FLUME_PID=$CYGNUS_PID_FILE
+        PID=$(cat ${CYGNUS_PID_FILE})        
+        FLUME_PID=$(ps -ef | grep -v "grep" | grep "${PID:-not_found}")
         if [[ -z ${FLUME_PID} ]]; then
             printf "%s\n" "$(failure)"
-            exit 1
+            result=$((${result}+1))
+            rm ${CYGNUS_PID_FILE}
         else
             chown ${CYGNUS_USER}:${CYGNUS_USER} ${CYGNUS_PID_FILE}
             printf "%s\n" "$(success)"
         fi
-    else
-        printf "%s\n" "Fail - ${FLUME_EXECUTABLE} not exists or is not executable."
-        exit 1
-    fi
+    done
+    return ${result}
 }
 
 cygnus_stop()
 {
-    printf "%-50s" "Stopping $NAME..."
-    if [[ -f "${CYGNUS_PID_FILE}" ]]; then
-        kill -HUP $(cat ${CYGNUS_PID_FILE})
-        rm -f ${CYGNUS_PID_FILE}
-        printf "%s\n" "$(success)"
-    else
-        printf "%s\n" "$(failure)"
+    local result=0
+
+    if [[ $(ls -l /var/run/cygnus/cygnus_*.pid 2> /dev/null | wc -l) -eq 0 ]]; then
+        printf "%s\n" "There aren't any instance of Cygnus running $(success)"
+        return 0
     fi
+
+    for run_instance in $(ls /var/run/cygnus/cygnus_*.pid)
+    do
+
+        local NAME
+        NAME=${run_instance%.pid}
+        NAME=${NAME#*cygnus_}
+
+        printf "%-50s" "Stopping Cygnus ${NAME}..."
+        PID=$(cat ${run_instance})        
+        kill -HUP ${PID} &> /dev/null
+        sleep 2
+        FLUME_PID=$(ps -ef | grep -v "grep" | grep "${PID:-not_found}")
+        if [[ -z ${FLUME_PID} ]]; then
+            rm -f ${run_instance}
+            printf "%s\n" "$(success)"
+        else
+            printf "%s\n" "$(failure)"
+            result=$((${result}+1))
+            rm -f ${run_instance}
+        fi
+    done
+    return ${result}
 }
 
 cygnus_status()
 {
-    status -p ${CYGNUS_PID_FILE} ${FLUME_EXECUTABLE}
+    local result=0
+
+    if [[ $(ls -l /var/run/cygnus/cygnus_*.pid 2> /dev/null | wc -l) -eq 0 ]]; then
+        printf "%s\n" "There aren't any instance of Cygnus running"
+        exit 1
+    fi
+
+    for run_instance in $(ls /var/run/cygnus/cygnus_*.pid)
+    do
+
+        local NAME
+        NAME=${run_instance%.pid}
+        NAME=${NAME#*cygnus_}
+
+        printf "%s\n" "Cygnus ${NAME} status..."
+        status -p ${run_instance} ${FLUME_EXECUTABLE}
+        result=$((${result}+${?}))
+
+    done
+    return ${result}
 }
 
 
 case ${PARAM} in
 
     'start')
-        status -p ${CYGNUS_PID_FILE} ${FLUME_EXECUTABLE} && exit 0
         cygnus_start
         ;;
 
     'stop')
-        status -p ${CYGNUS_PID_FILE} ${FLUME_EXECUTABLE} || exit 0
         cygnus_stop
         ;;
 
